# Generated by Django 5.2.12 on 2026-04-05 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=128)),
                ("occurred_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["occurred_at"], name="finance_fin_occurre_0cb765_idx"
                    ),
                    models.Index(
                        fields=["category"], name="finance_fin_categor_f898e6_idx"
                    ),
                    models.Index(fields=["type"], name="finance_fin_type_0beaac_idx"),
                    models.Index(
                        fields=["deleted_at"], name="finance_fin_deleted_5b1792_idx"
                    ),
                ],
            },
        ),
    ]
